### ISSUE TITLE
MochaとLinterはいいぞ

### ISSUE THREAD

**Issue by ghost** [mnmonzk/wikipedia-bot#14]
ふわああぁ！ いらっしゃぁい！ よぉこそぉ↑Issue #14 へ～！ どうぞどうぞ、ゆっぐりしてってぇ！

いやまﾞっ↓てたよぉ！ やっとお客さんが来てくれたゆぉ！ 嬉しいなあ！ ねえなんにぃ書くぅ？ 色々あるよぉ、これね、テストコードって言うんだってぇ、ハ↓カセに教えてもらったンの！ここからMochaが出るからそれを使ってにぇ…

ん？

テストコード書かないしESLintも使わないのかぁ...ペッ

**Comment by 10mocy** [comment]
詳しく教えて♥

**Comment by ghost** [comment]
[テストフレームワーク(Mocha) https://mochajs.org/](https://mochajs.org/)
[Linter(ESLint) https://eslint.org/](https://eslint.org/)
[スタイルガイド(Airbnb) https://github.com/airbnb/javascript](https://github.com/airbnb/javascript)

全部英語のフレンズなんだね！わーい！すごーい！たーのしー！
