### ISSUE TITLE
RTへの対応

### ISSUE THREAD

**Issue by ghost** [mnmonzk/wikipedia-bot#7]
`#とは`が付いたツイートをRTすると、RTした人にもリプライが飛んでくる  
![screenshot_2017-09-14_17-57-42](https://user-images.githubusercontent.com/25413599/30421646-5c3e7180-9978-11e7-9608-b73eb32e0a53.png)

**Comment by 10mocy** [comment]
気づかなかった

**Comment by ghost** [comment]
気が付いて

**Comment by siketyan** [comment]
対応します

**Comment by siketyan** [comment]
Pull Requestにて対応しました。

**Comment by 10mocy** [comment]
実装をマージし、問題が解決したのでクローズする。

**Comment by acid-chicken** [comment]
Why is this issue labeled 'bug'?

**Comment by 10mocy** [comment]
@acid-chicken タイトルとの矛盾的何か。ラベリングを変更する。

**Comment by acid-chicken** [comment]
Nice work ;)
